import type {Metadata} from 'next';
import './globals.css';
import {QueryProvider} from '@/Providers/QueryProvider';
import {ReactNode} from 'react';

export const metadata: Metadata = {
  title: 'Azki-task',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
